"""
This module performs grammatical correction on audio files. It currently supports .wav files.
"""

#Import libraries
import os
import speech_recognition as sr
from langchain_community.llms import Ollama
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import OpenAI

def user_input_audio(audio):

    """Takes user input as audio and highlights grammatical errors and displays corrected text"""

    #Get OPENAI_API_KEY
    key = os.getenv("OPENAI_API_KEY")

    #Define the LLM
    llm = OpenAI(model="gpt-3.5-turbo-instruct", api_key=key)

    #Create the prompt
    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a english grammar specialist to check if there are any grammatical errors in the text generated by the audio provided by the user. You have to display the original text generated by the audio and highlight the grammatical errors in the original text and finally correct the grammatical errors and show the correct text. The highlighted errors should display the grammatical errors."  ),
        ("user", "{input}")
    ])

    #Parse the output
    output_parser = StrOutputParser()

    #Create a recognizer instance
    recognizer_instance = sr.Recognizer()

    #Passing audio file as source
    with sr.AudioFile(audio) as source:
        audio_text = recognizer_instance.listen(source)
        try:
            #Using google speech recognition to convert to text
            text = recognizer_instance.recognize_google(audio_text)
            print('Converting audio transcripts into text...')
            print(text)
        except:
            print('Sorry.. Please run again...')

    #Creating lang chain
    chain = prompt | llm | output_parser

    #Calling invoke with a single input
    return chain.invoke({"input": text})
